; EBNF for simple Regualar Expression language
; handles like: (ab|cd), foo+, ba*r
RegExp ::= Letter | Sequence | Alternation | Repetition | Group
Sequence ::= RegExp Sequence
         | RegExp
Alternation ::= RegExp '|' RegExp
Repetition ::= ZeroOrMore | OneOrMore | Option
ZeroOrMore ::= RegExp '*'
OneOrMore ::= RegExp '+'
Option ::= RegExp '?'
Group ::= '(' RegExp ')'
Letter ::= [a-zA-Z0-9]