<uON> ::= <Num> | <Object> ;
 <Object> ::= '{' <List>? '}' ;
<List> ::= <Pair> ',' <List> ;
    | <Pair> ;
 <Pair> ::=  <Key> ':' <Value> ;
<Key> ::= '"' [a-zA-Z]+ '"' ;
value ::= <Num> | <Object> ;
<Num> ::= <NonZero> ('0' | <NonZero>) ;
<NonZero> ::= [1-9] ;
