 ; EBNF for uON or Micro JSON

;  exampples of uON
; 199
; { "Addr": { "StreetNumber": 1234 } }
; { "Foo": 1807, "Bar": 277 }
; This is a NonTerminal. This is a 'terminal'
; The following line is an example rule showing the above and EBNF operators
; NonTerminal ::= ('terminal' | NonTerminal)+
uON ::= Num | Object
 Object ::= '{' List? '}'
List ::= Pair ',' List
    | Pair
 Pair ::=  Key ':' Value
Key ::= '"' [a-zA-Z]+ '"'
value ::= Num | Object
Num ::= NonZero ('0' | NonZero)
NonZero ::= [1-9]
